apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
        - name: customer-api
          image: customer-api:latest # Change to your registry/image:tag for production
          ports:
            - containerPort: 8080
          env:
            # Example: pass custom environment variables here
            # - name: SPRING_DATASOURCE_URL
            #   value: jdbc:h2:mem:testdb
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: customer-api-service
spec:
  type: NodePort
  selector:
    app: customer-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 